font_family   Maple Mono NF
font_size   11

cursor_shape   beam
cursor_trail   1
cursor_trail_decay 0.1 0.4
cursor_trail_start_threshold 1
cursor_trail_color none

background_opacity   0.25
window_padding_width 15

repaint_delay 18
input_delay 5
sync_to_monitor no
wayland_enable_ime no
