#!/bin/bash

# Installation + setting up of yay
sudo pacman -S --needed base-devel git
git clone https://aur.archlinux.org/yay-bin.git
cd yay-bin
makepkg -si
cd

# Installation of apps
sudo pacman -S zsh i3blocks gtklock NetworkManager cava cmatrix bluetui fzf unzip emptty azote rofi foot flatpak fastfetch libreoffice python-pywal thefuck btop vim i3blocks

yay -S localsend-bin swayfx themix-full-git

flatpak install flathub md.obsidian.Obsidian

mkdir scripts
cd scripts

# These apps you can't get directly form the AUR or from the repos, so I curl/git clone in the AppImage/Tarball manually
echo ""
echo "kdenlive (Video Editor)"
curl -O -# https://download.kde.org/stable/kdenlive/25.08/linux/kdenlive-25.08.3-x86_64.AppImage
echo ""
echo "SuperTuxKart (Peak Game)"
curl -O -# https://github.com/supertuxkart/stk-code/releases/download/1.5/SuperTuxKart-1.5-linux-x86_64.tar.gz
echo ""
echo "WaterFox (Browser)"
curl -O -# https://cdn1.waterfox.net/waterfox/releases/6.6.6/Linux_x86_64/waterfox-6.6.6.tar.bz2
tar -xf waterfox-6.6.6.tar.bz2
rm waterfox-6.6.6.tar.bz2
cd
echo ""
echo "Persway (cool tiling addon)"
git clone https://github.com/johnae/persway.git
echo ""
echo "NPM setup (boring coding stuff)"
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash

# Setting up zsh and ohmyzsh
sudo chsh -s $(which zsh)
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
rm .zshrc
ln -s ~/notharibsRice/.zshrc ~/

# Set up of config files
cp ~/notharibsRice/.vimrc ~/

mkdir -p ~/.config
mkdir -p ~/.config/sway/
mkidr -p ~/.config/rofi/
mkidr -p ~/.config/i3blocks
mkdir -p ~/.config/foot/

ln -s ~/notharibsRice/configs/sway/config ~/.config/sway/
ln -s ~/notharibsRice/configs/rofi/config.rasi ~/.config/rofi/
ln -s ~/notharibsRice/configs/i3blocks/config ~/.config/i3blocks/
ln -s ~/notharibsRice/configs/foot/foot.ini ~/.config/foot/
