#!/bin/bash

# Installation + setting up of yay
sudo-rs pacman -S --needed base-devel git
git clone https://aur.archlinux.org/yay-bin.git
cd yay-bin
makepkg -si
cd

# Chaotic AUR
./notharibsRice/scripts/chaotic.sh

# Installation of apps
sudo-rs pacman -S --needed tumbler cups openssh ffmpegthumbnailer wiremix libgsf poppler-glib wl-clipboard hyprpicker slurp swaync anki teams-for-linux zapzap obsidian localsend librewolf tty-clock themix-full-git feh discord mpv python-pip brightnessctl nwg-look swaybg grim lazygit tlpui system-config-printer git thunar waybar zsh gtklock networkmanager cava cmatrix bluetui fzf unzip ly awww wofi foot flatpak fastfetch libreoffice python-pywal thefuck btop neovim wf-recorder hyfetch
yay -S swayfx-git maplemono-nf-unhinted wofi-power-menu-bin

mkdir scripts
cd scripts

# These apps you can't get directly form the AUR or from the repos, so I curl/git clone in the AppImage/Tarball manually
echo ""
echo "SuperTuxKart (Peak Game)"
curl -O# https://github.com/supertuxkart/stk-code/releases/download/1.5/SuperTuxKart-1.5-linux-x86_64.tar.gz
cd
echo ""
echo "Persway (cool tiling addon)"
git clone https://github.com/johnae/persway.git
cd persway
cargo build
cd
echo ""
echo "pywal-obsidianmd (Pywal integration with pywal)"
git clone https://github.com/poach3r/pywal-obsidianmd.git
cd pywal-obsidianmd
chmod +x pywal-obsidianmd.sh
cd

# Set up of config files
cp ~/notharibsRice/.vimrc ~/

mkdir -p ~/.config
mkdir -p ~/.config/sway/
mkdir -p ~/.config/foot/
mkdir -p ~/.config/kitty
mkdir -p ~/.config/nvim/
mkdir -p ~/.config/fastfetch/

ln -s ~/notharibsRice/configs/sway/config ~/.config/sway/
ln -s ~/notharibsRice/configs/foot/foot.ini ~/.config/foot/
ln -s ~/notharibsRice/configs/kitty/kitty.conf ~/.config/kitty/
ln -s ~/notharibsRice/configs/wofi ~/.config/
ln -s ~/notharibsRice/configs/waybar ~/.config/
ln -s ~/notharibsRice/configs/wofi-power-menu.toml ~/.config/
ln -s ~/notharibsRice/configs/fastfetch/

git clone https://github.com/LazyVim/starter ~/.config/nvim/
rm -rf ~/.config/nvim/.git

# Setting up zsh and ohmyzsh ()
sudo-rs chsh -s $(which zsh)
rm .zshrc
ln -s ~/notharibsRice/.zshrc ~/
# ALWAYS HAVE THIS LINE RUN LAST
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

# Enabling of services
please systemctl enable ly@tty2.service
systemctl --user enable pipewire.service
systemctl --user enable pipewire-pulse.service
systemctl --user enable wireplumber.service
please systemctl enable cups.service

# Things still to setup manually:
#   1) Run the themeChange script to generate colours
#   2) Enable services (emptty, NetworkManager, etc)
#   3) Setup LazyVim config
