#!/bin/bash

# Installation + setting up of yay
sudo pacman -S --needed base-devel git
git clone https://aur.archlinux.org/yay-bin.git
cd yay-bin
makepkg -si
cd

# Chaotic AUR
./notharibsRice/chaotic.sh

# Installation of apps
sudo pacman -S --needed wl-clipboard hyprpicker slurp swaync anki teams_for_linux zapzap obsidian localsend librewolf tty-clock themix-full-git ttf-jetbrains-mono-nerd papirus-icon-theme feh discord mpv python-pip brightnessctl nwg-look swaybg grim lazygit tlpui system-config-printer git thunar waybar zsh gtklock NetworkManager cava cmatrix bluetui fzf unzip ly azote wofi foot flatpak fastfetch libreoffice python-pywal thefuck btop neovim wf-recorder
yay -S swayfx-git

mkdir scripts
cd scripts

# These apps you can't get directly form the AUR or from the repos, so I curl/git clone in the AppImage/Tarball manually
echo ""
echo "SuperTuxKart (Peak Game)"
curl -O# https://github.com/supertuxkart/stk-code/releases/download/1.5/SuperTuxKart-1.5-linux-x86_64.tar.gz
cd
echo ""
echo "Persway (cool tiling addon)"
git clone https://github.com/johnae/persway.git
cd persway
cargo build
cd
echo ""
echo "pywal-obsidianmd (Pywal integration with pywal)"
git clone https://github.com/poach3r/pywal-obsidianmd.git
cd pywal-obsidianmd
chmod +x pywal-obsidianmd.sh
cd

# Set up of config files
cp ~/notharibsRice/.vimrc ~/

mkdir -p ~/.config
mkdir -p ~/.config/sway/
mkdir -p ~/.config/foot/
mkdir -p ~/.config/kitty
mkdir -p ~/.config/nvim/
mkdir -p ~/.config/wofi/
mkdir -p ~/.config/waybar/

ln -s ~/notharibsRice/configs/sway/config ~/.config/sway/
ln -s ~/notharibsRice/configs/foot/foot.ini ~/.config/foot/
ln -s ~/notharibsRice/configs/kitty/kitty.conf ~/.config/kitty/
ln -s ~/notharibsRice/configs/wofi/config ~/.config/wofi/
ln -s ~/notharibsRice/configs/wofi/style.css ~/.config/wofi/
ln -s ~/notharibsRice/configs/waybar/config ~/.config/waybar/
ln -s~/notharibsRice/configs/waybar/style.css ~/.config/waybar/

git clone https://github.com/LazyVim/starter ~/.config/nvim/
rm -rf ~/.config/nvim/.git

# Setting up zsh and ohmyzsh ()
sudo chsh -s $(which zsh)
rm .zshrc
ln -s ~/notharibsRice/.zshrc ~/
# ALWAYS HAVE THIS LINE RUN LAST
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

# Things still to setup manually:
#   1) First Time Azote run
#   2) Run the themeChange script to generate colours
#   3) Enable services (emptty, NetworkManager, etc)
#   4) Setup LazyVim config
